# Generated by Django 3.1.2 on 2020-10-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data/hora de criação do agendamento')),
                ('message_type', models.CharField(choices=[('sms', 'Mensagem SMS'), ('whatsapp', 'Mensagem Whatsapp'), ('push', 'Notificação Push'), ('email', 'E-mail')], max_length=8, verbose_name='Tipo de mensagem')),
                ('scheduling', models.DateTimeField(verbose_name='Data/hora de agendamento para envio')),
                ('message', models.TextField(verbose_name='Mensagem a ser entregue')),
                ('recipient', models.TextField(verbose_name='Destinatário de mensagem')),
            ],
        ),
    ]
