# Generated by Django 3.1.2 on 2020-10-11 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='CommunicationScheduling',
        ),
    ]
