# Generated by Django 3.1.2 on 2020-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201011_0226'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationscheduling',
            name='status',
            field=models.CharField(choices=[('waiting', 'Aguardando'), ('running', 'Executando envio'), ('done', 'Envio realizado'), ('error', 'Erro')], default='waiting', max_length=7, verbose_name='Status do agendamento'),
        ),
        migrations.AlterField(
            model_name='communicationscheduling',
            name='message_type',
            field=models.CharField(choices=[('sms', 'Mensagem SMS'), ('sending', 'Mensagem Whatsapp'), ('push', 'Notificação Push'), ('email', 'E-mail')], max_length=8, verbose_name='Tipo de mensagem'),
        ),
    ]
